service: my-serverless-service

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  webhookHandler:
    handler: handler.webhookHandler
    events:
      - http:
          path: webhook
          method: post
